spring:
  application.name: spring-boot-examplo
  
server:
 port: 8083
 contextPath: /spring-boot-examplo
 
---
spring:
  profiles: local

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: user
    password: 123
  jpa:
    database: oracle
    show-sql: true
    hibernate.ddl-auto: update
---